export const GameActions = {
    START_NEW_PATH: 'START_NEW_PATH',
    ADD_CELL_TO_PATH: 'ADD_CELL_TO_PATH',
    REMOVE_LAST_CELL_FROM_PATH: 'REMOVE_LAST_CELL_FROM_PATH',
    COMPLETE_PATH: 'COMPLETE_PATH',
    RESET_ACTIVE_PATH: 'RESET_ACTIVE_PATH',
    RESET: 'RESET'
} as const;
